// https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes
// https://en.wikipedia.org/wiki/List_of_ISO_639-2_codes
// https://cloud.google.com/translate/docs/languages
// https://docs.google.com/spreadsheets/d/1gg8ZuQiNilgnh3nRiEw44vnANl2i4ypsAe04fYUBtiE/edit?usp=sharing
const supportedLanguages = [
  // ["ab", "AB", "аҧсуа бызшәа, аҧсшәа", "Abkhazian"],
  // ["aa", "AA", "Afaraf", "Afar"],
  ["af", "AF", "Afrikaans", "Afrikaans"],
  // ["ak", "AK", "Akan", "Akan"],
  ["sq", "SQ", "Shqip", "Albanian"],
  ["am", "AM", "አማርኛ", "Amharic"],
  ["ar", "AR", "العربية", "Arabic"],
  // ["an", "AN", "aragonés", "Aragonese"],
  ["hy", "HY", "Հայերեն", "Armenian"],
  // ["as", "AS", "অসমীয়া", "Assamese"],
  // ["av", "AV", "авар мацӀ, магӀарул мацӀ", "Avaric"],
  // ["ae", "AE", "avesta", "Avestan"],
  // ["ay", "AY", "aymar aru", "Aymara"],
  // ["az", "AZ", "azərbaycan dili", "Azerbaijani"],
  // ["bm", "BM", "bamanankan", "Bambara"],
  // ["ba", "BA", "башҡорт теле", "Bashkir"],
  ["eu", "EU", "euskara, euskera", "Basque"],
  ["be", "BE", "беларуская мова", "Belarusian"],
  ["bn", "BN", "বাংলা", "Bengali"],
  // ["bh", "BH", "भोजपुरी", "Bihari languages"],
  // ["bi", "BI", "Bislama", "Bislama"],
  ["bs", "BS", "bosanski jezik", "Bosnian"],
  // ["br", "BR", "brezhoneg", "Breton"],
  ["bg", "BG", "български език", "Bulgarian"],
  ["my", "MY", "ဗမာစာ", "Burmese"],
  ["ca", "CA", "català, valencià", "Catalan, Valencian"], // opt. 1
  // ["ch", "CH", "Chamoru", "Chamorro"],
  // ["ce", "CE", "нохчийн мотт", "Chechen"],
  ["ceb", "CEB", "Sinugbuanong Binisayâ", "Cebuano"], // ISO 639-2
  ["ny", "NY", "chiCheŵa, chinyanja", "Chichewa, Chewa, Nyanja"],
  // ["zh", "ZH", "中文 (Zhōngwén), 汉语, 漢語", "Chinese"], (x)
  ["zh-TW", "ZH", "漢語", "Classical Chinese"],
  ["zh-CN", "ZH", "中文", "Chinese"],
  // ["cv", "CV", "чӑваш чӗлхи", "Chuvash"],
  // ["kw", "KW", "Kernewek", "Cornish"],
  ["co", "CO", "corsu, lingua corsa", "Corsican"],
  // ["cr", "CR", "ᓀᐦᐃᔭᐍᐏᐣ", "Cree"],
  ["hr", "HR", "hrvatski jezik", "Croatian"],
  ["cs", "CS", "čeština, český jazyk", "Czech"],
  ["da", "DA", "dansk", "Danish"],
  // ["dv", "DV", "ދިވެހި", "Divehi, Dhivehi, Maldivian"],
  ["nl", "NL", "Nederlands, Vlaams", "Dutch, Flemish"], // opt. 1
  // ["dz", "DZ", "རྫོང་ཁ", "Dzongkha"],
  ["en", "EN", "English", "English"],
  ["eo", "EO", "Esperanto", "Esperanto"],
  ["et", "ET", "eesti, eesti keel", "Estonian"],
  // ["ee", "EE", "Eʋegbe", "Ewe"],
  // ["fo", "FO", "føroyskt", "Faroese"],
  // ["fj", "FJ", "vosa Vakaviti", "Fijian"],
  ["fi", "FI", "suomi, suomen kieli", "Finnish"],
  ["fr", "FR", "Français" /*français, langue française"*/, "French"],
  // ["ff", "FF", "Fulfulde, Pulaar, Pular", "Fulah"],
  ["gl", "GL", "Galego", "Galician"], // opt. 1
  ["ka", "KA", "ქართული", "Georgian"],
  ["de", "DE", "Deutsch", "German"],
  ["el", "EL", "ελληνικά", "Greek, Modern (1453–)"],
  // ["gn", "GN", "Avañe'ẽ", "Guarani"],
  ["gu", "GU", "ગુજરાતી", "Gujarati"],
  ["ht", "HT", "Kreyòl ayisyen", "Haitian, Haitian Creole"],
  ["ha", "HA", "(Hausa) هَوُسَ", "Hausa"],
  ["haw", "HAW", "ʻŌlelo Hawaiʻi", "Hawaiian"], // ISO 639-2
  ["he", "HE", "עברית", "Hebrew"],
  // ["hz", "HZ", "Otjiherero", "Herero"],
  ["hi", "HI", "हिन्दी, हिंदी", "Hindi"],
  ["hmn", "HMN", "lus Hmoob", "Hmong"], // ISO 639-2
  // ["ho", "HO", "Hiri Motu", "Hiri Motu"],
  ["hu", "HU", "magyar", "Hungarian"],
  // ["ia", "IA", "Interlingua", "Interlingua (International Auxiliary Language Association)"],
  ["id", "ID", "Bahasa Indonesia", "Indonesian"],
  // ["ie", "IE", "(originally:) Occidental, (after WWII:) Interlingue", "Interlingue, Occidental"],
  ["ga", "GA", "Gaeilge", "Irish"],
  ["ig", "IG", "Asụsụ Igbo", "Igbo"],
  // ["ik", "IK", "Iñupiaq, Iñupiatun", "Inupiaq"],
  // ["io", "IO", "Ido", "Ido"],
  ["is", "IS", "Íslenska", "Icelandic"],
  ["it", "IT", "Italiano", "Italian"],
  // ["iu", "IU", "ᐃᓄᒃᑎᑐᑦ", "Inuktitut"],
  ["ja", "JA", "日本語 (にほんご)", "Japanese"],
  ["jv", "JV", "ꦧꦱꦗꦮ, Basa Jawa", "Javanese"],
  // ["kl", "KL", "kalaallisut, kalaallit oqaasii", "Kalaallisut, Greenlandic"],
  ["kn", "KN", "ಕನ್ನಡ", "Kannada"],
  // ["kr", "KR", "Kanuri", "Kanuri"],
  // ["ks", "KS", "कश्मीरी, كشميري‎", "Kashmiri"],
  ["kk", "KK", "қазақ тілі", "Kazakh"],
  ["km", "KM", "ខ្មែរ, ខេមរភាសា, ភាសាខ្មែរ", "Central Khmer"],
  // ["ki", "KI", "Gĩkũyũ", "Kikuyu, Gikuyu"],
  ["rw", "RW", "Ikinyarwanda", "Kinyarwanda"], // opt. 1
  ["ky", "KY", "Кыргызча, Кыргыз тили", "Kirghiz, Kyrgyz"],
  // ["kv", "KV", "коми кыв", "Komi"],
  // ["kg", "KG", "Kikongo", "Kongo"],
  ["ko", "KO", "한국어", "Korean"],
  ["ku", "KU", "Kurdî, کوردی‎", "Kurdish"], // opt. 1
  // ["kj", "KJ", "Kuanyama", "Kuanyama, Kwanyama"],
  ["la", "LA", "latine, lingua latina", "Latin"], // opt. 1
  ["lb", "LB", "Lëtzebuergesch", "Luxembourgish, Letzeburgesch"],
  // ["lg", "LG", "Luganda", "Ganda"],
  // ["li", "LI", "Limburgs", "Limburgan, Limburger, Limburgish"],
  // ["ln", "LN", "Lingála", "Lingala"],
  ["lo", "LO", "ພາສາລາວ", "Lao"], // opt. 1
  ["lt", "LT", "lietuvių kalba", "Lithuanian"],
  // ["lu", "LU", "Kiluba", "Luba-Katanga"],
  ["lv", "LV", "latviešu valoda", "Latvian"],
  // ["gv", "GV", "Gaelg, Gailck", "Manx"],
  ["mk", "MK", "македонски јазик", "Macedonian"],
  ["mg", "MG", "fiteny malagasy", "Malagasy"], // opt. 1
  ["ms", "MS", "Bahasa Melayu, بهاس ملايو‎", "Malay"], // opt. 1
  ["ml", "ML", "മലയാളം", "Malayalam"],
  ["mt", "MT", "Malti", "Maltese"],
  ["mi", "MI", "te reo Māori", "Maori"],
  ["mr", "MR", "मराठी", "Marathi"],
  // ["mh", "MH", "Kajin M̧ajeļ", "Marshallese"],
  ["mn", "MN", "Монгол хэл", "Mongolian"],
  // ["na", "NA", "Dorerin Naoero", "Nauru"],
  // ["nv", "NV", "Diné bizaad", "Navajo, Navaho"],
  // ["nd", "ND", "isiNdebele", "North Ndebele"],
  ["ne", "NE", "नेपाली", "Nepali"], // opt. 1
  // ["ng", "NG", "Owambo", "Ndonga"],
  // ["nb", "NB", "Norsk Bokmål", "Norwegian Bokmål"], (x)
  // ["nn", "NN", "Norsk Nynorsk", "Norwegian Nynorsk"], (x)
  ["no", "NO", "Norsk", "Norwegian"],
  // ["ii", "II", "ꆈꌠ꒿ Nuosuhxop", "Sichuan Yi, Nuosu"],
  // ["nr", "NR", "isiNdebele", "South Ndebele"],
  // ["oc", "OC", "occitan, lenga d'òc", "Occitan"],
  // ["oj", "OJ", "ᐊᓂᔑᓈᐯᒧᐎᓐ", "Ojibwa"],
  // [
  //   "cu",
  //   "CU",
  //   "ѩзыкъ словѣньскъ",
  //   "Church Slavic, Old Slavonic, Church Slavonic, Old Bulgarian, Old Church Slavonic",
  // ],
  // ["om", "OM", "Afaan Oromoo", "Oromo"],
  ["or", "OR", "ଓଡ଼ିଆ", "Oriya"], // opt. 1
  // ["os", "OS", "ирон æвзаг", "Ossetian, Ossetic"],
  ["pa", "PA", "ਪੰਜਾਬੀ, پنجابی‎", "Punjabi, Panjabi"], // opt. 1
  // ["pi", "PI", "पालि, पाळि", "Pali"],
  ["fa", "FA", "فارسی", "Persian"],
  ["pl", "PL", "język polski, polszczyzna", "Polish"],
  ["ps", "PS", "پښتو", "Pashto, Pushto"], // opt. 1
  ["pt", "PT", "Português", "Portuguese"],
  // ["qu", "QU", "Runa Simi, Kichwa", "Quechua"],
  // ["rm", "RM", "Rumantsch Grischun", "Romansh"],
  // ["rn", "RN", "Ikirundi", "Rundi"],
  ["ro", "RO", "Română", "Romanian, Moldavian, Moldovan"],
  ["ru", "RU", "русский", "Russian"],
  // ["sa", "SA", "संस्कृतम्", "Sanskrit"],
  // ["sc", "SC", "sardu", "Sardinian"],
  ["sd", "SD", "सिन्धी, سنڌي، سندھی‎", "Sindhi"],
  // ["se", "SE", "Davvisámegiella", "Northern Sami"],
  ["sm", "SM", "gagana fa'a Samoa", "Samoan"],
  // ["sg", "SG", "yângâ tî sängö", "Sango"],
  ["sr", "SR", "српски језик", "Serbian"],
  ["gd", "GD", "Gàidhlig", "Gaelic, Scottish Gaelic"],
  ["sn", "SN", "chiShona", "Shona"],
  ["si", "SI", "සිංහල", "Sinhala, Sinhalese"],
  ["sk", "SK", "Slovenčina, Slovenský Jazyk", "Slovak"],
  ["sl", "SL", "Slovenski Jezik, Slovenščina", "Slovenian"],
  ["so", "SO", "Soomaaliga, af Soomaali", "Somali"],
  ["st", "ST", "Sesotho", "Southern Sotho"], // opt. 1
  ["es", "ES", "Español", "Spanish, Castilian"], // opt. 1
  ["su", "SU", "Basa Sunda", "Sundanese"],
  ["sw", "SW", "Kiswahili", "Swahili"], // opt. 1
  // ["ss", "SS", "SiSwati", "Swati"],
  ["sv", "SV", "Svenska", "Swedish"],
  ["ta", "TA", "தமிழ்", "Tamil"],
  ["te", "TE", "తెలుగు", "Telugu"],
  ["tg", "TG", "тоҷикӣ, toçikī, تاجیکی‎", "Tajik"],
  ["th", "TH", "ไทย", "Thai"], // opt. 1
  // ["ti", "TI", "ትግርኛ", "Tigrinya"],
  // ["bo", "BO", "བོད་ཡིག", "Tibetan"],
  ["tk", "TK", "Türkmen, Түркмен", "Turkmen"],
  ["tl", "TL", "Wikang Tagalog", "Tagalog"], // opt. 1
  // ["tn", "TN", "Setswana", "Tswana"],
  // ["to", "TO", "Faka Tonga", "Tonga (Tonga Islands)"],
  ["tr", "TR", "Türkçe", "Turkish"],
  // ["ts", "TS", "Xitsonga", "Tsonga"],
  ["tt", "TT", "татар теле, tatar tele", "Tatar"],
  // ["tw", "TW", "Twi", "Twi"],
  // ["ty", "TY", "Reo Tahiti", "Tahitian"],
  ["ug", "UG", "ئۇيغۇرچە‎, Uyghurche", "Uighur, Uyghur"],
  ["uk", "UK", "Українська", "Ukrainian"],
  ["ur", "UR", "اردو", "Urdu"],
  ["uz", "UZ", "Oʻzbek, Ўзбек, أۇزبېك‎", "Uzbek"],
  // ["ve", "VE", "Tshivenḓa", "Venda"],
  ["vi", "VI", "Tiếng Việt", "Vietnamese"],
  // ["vo", "VO", "Volapük", "Volapük"],
  // ["wa", "WA", "Walon", "Walloon"],
  ["cy", "CY", "Cymraeg", "Welsh"],
  // ["wo", "WO", "Wollof", "Wolof"],
  ["fy", "FY", "Frysk", "Western Frisian"], // opt. 1
  ["xh", "XH", "isiXhosa", "Xhosa"], // opt. 1
  ["yi", "YI", "ייִדיש", "Yiddish"],
  ["yo", "YO", "Yorùbá", "Yoruba"],
  // ["za", "ZA", "Saɯ cueŋƅ, Saw cuengh", "Zhuang, Chuang"],
  ["zu", "ZU", "isiZulu", "Zulu"], // opt. 1
];

const languageCodes = [
  "af",
  "sq",
  "am",
  "ar",
  "hy",
  "eu",
  "be",
  "bn",
  "bs",
  "bg",
  "my",
  "ca",
  "ceb",
  "ny",
  "zh-TW",
  "zh-CN",
  "co",
  "hr",
  "cs",
  "da",
  "nl",
  "en",
  "eo",
  "et",
  "fi",
  "fr",
  "gl",
  "ka",
  "de",
  "el",
  "gu",
  "ht",
  "ha",
  "haw",
  "he",
  "hi",
  "hmn",
  "hu",
  "id",
  "ga",
  "ig",
  "is",
  "it",
  "ja",
  "jv",
  "kn",
  "kk",
  "km",
  "rw",
  "ky",
  "ko",
  "ku",
  "la",
  "lb",
  "lo",
  "lt",
  "lv",
  "mk",
  "mg",
  "ms",
  "ml",
  "mt",
  "mi",
  "mr",
  "mn",
  "ne",
  "no",
  "or",
  "pa",
  "fa",
  "pl",
  "ps",
  "pt",
  "ro",
  "ru",
  "sd",
  "sm",
  "sr",
  "gd",
  "sn",
  "si",
  "sk",
  "sl",
  "so",
  "st",
  "es",
  "su",
  "sw",
  "sv",
  "ta",
  "te",
  "tg",
  "th",
  "tk",
  "tl",
  "tr",
  "tt",
  "ug",
  "uk",
  "ur",
  "uz",
  "vi",
  "cy",
  "fy",
  "xh",
  "yi",
  "yo",
  "zu",
];

function mapLanguageCodes(codes, favorites = []) {
  const sorting = [...favorites, ...codes.filter((code) => !favorites.includes(code))];
  return {
    favorites: favorites.length > 0 ? favorites : null,
    codes: supportedLanguages
      .filter(([code]) => codes.includes(code))
      .sort(([a], [b]) => {
        return sorting.indexOf(a) - sorting.indexOf(b);
      }),
  };
}

module.exports = { supportedLanguages, languageCodes, mapLanguageCodes };
