name: Prerelease
on: workflow_dispatch
env:
  BASE: /next/
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 12
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install yarn
        run: npm -g i yarn
      - name: Install Dependencies
        run: yarn
      - name: Initialize asterics-docs
        run: yarn docs init --no-reference
      - name: Setup docs
        run: yarn docs setup
      - name: Build
        run: yarn build
      - name: Get Code (gh-pages)
        uses: actions/checkout@v3
        with:
          ref: "gh-pages"
          path: "gh-pages"
      - name: Deploy
        run: |
          rm -rf gh-pages/next
          cp -r dist gh-pages/next
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "<>"
          git --git-dir=gh-pages/.git --work-tree=gh-pages/ add .
          git --git-dir=gh-pages/.git --work-tree=gh-pages/ status
          git --git-dir=gh-pages/.git --work-tree=gh-pages/ commit -m "docs: prerelease"
          git --git-dir=gh-pages/.git --work-tree=gh-pages/ log -2
          git --git-dir=gh-pages/.git --work-tree=gh-pages/ push
