name: Prerelease
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Log Version
        run: |
          node -v
          npm -v
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 12
      - name: Log Version
        run: |
          node -v
          npm -v
