name: Prerelease
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # At 00:00 (daily)
env:
  BASE: /next/
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install NodeGit Build Dependencies
        run: sudo apt install libkrb5-dev
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7.25.1
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: pnpm
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Initialize asterics-docs
        run: pnpm run docs init --no-reference
      - name: Setup docs
        run: pnpm run docs setup
      - name: Build
        env:
          NODE_OPTIONS: "--max-old-space-size=12288"
        run: pnpm run build
      - name: Upload Build Result
        uses: actions/upload-artifact@v3
        with:
          name: asterics-docs
          path: dist
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Build Result
        uses: actions/download-artifact@v3
        with:
          name: asterics-docs
          path: asterics-docs
      - name: Get Code (gh-pages)
        uses: actions/checkout@v3
        with:
          ref: "gh-pages"
          path: "gh-pages"
      - name: Merge Builds
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email ""
          rm -rf gh-pages/next
          cp -r asterics-docs gh-pages/next
          git --git-dir=gh-pages/.git --work-tree=gh-pages/ add .
          git --git-dir=gh-pages/.git --work-tree=gh-pages/ commit -m "docs: prerelease"
      - name: Upload to GitHub
        run: git --git-dir=gh-pages/.git --work-tree=gh-pages/ push
