name: Release
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0" # At 00:00 on Sunday (weekly)
env:
  BASE: /
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 12
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install yarn
        run: npm -g i yarn
      - name: Install Dependencies
        run: yarn
      - name: Initialize asterics-docs
        run: yarn docs init --no-reference
      - name: Setup docs
        run: yarn docs setup
      - name: Build
        run: yarn build
      - name: Get Code (gh-pages)
        uses: actions/checkout@v3
        with:
          ref: "gh-pages"
          path: "gh-pages"
      - name: Set User
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email ""
      - name: Deploy
        run: |
          mv gh-pages/next next
          rm -rf gh-pages/*
          cp -r dist/* gh-pages/
          mv next gh-pages/next
          echo "www.asterics.eu" > gh-pages/CNAME
          git --git-dir=gh-pages/.git --work-tree=gh-pages/ add .
          git --git-dir=gh-pages/.git --work-tree=gh-pages/ commit -m "docs: release"
          git --git-dir=gh-pages/.git --work-tree=gh-pages/ push
